spring:
  datasource:
    url: jdbc:h2:mem:crm-db
    driver-class-name: org.h2.Driver
    username: sa
    password:
    initialization-mode: always

    h2:
      console:
        enabled: true
        path: /h2-console